=== SSergio0-UO/sew/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
	targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud-pista" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="numero-vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="punto-origen" />
				<xs:element ref="puntos-anonimos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud-pista">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="uds" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="uds" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="numero-vueltas" type="xs:int" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="archivo" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="archivo" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto-origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud-origen" />
				<xs:element ref="latitud-origen" />
				<xs:element ref="altitud-origen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud-origen">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="-180"></xs:minInclusive>
				<xs:maxInclusive value="180"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="latitud-origen">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="-90"></xs:minInclusive>
				<xs:maxInclusive value="90"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="altitud-origen">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"></xs:minInclusive>
				<xs:maxInclusive value="5000"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="puntos-anonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenada" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="uds" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:decimal" />
	<xs:element name="latitud" type="xs:decimal" />
	<xs:element name="altitud" type="xs:decimal" />
	<xs:element name="sector" type="xs:decimal" />
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="tiempo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tiempo" type="xs:string" />
	<xs:element name="clasificacion">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="nombre" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SSergio0-UO/sew/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.uniovi.es"
             xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <nombre>Jerez-Angel Nieto</nombre>
    <longitud-pista uds="Kilometros">4,42</longitud-pista>
    <anchura uds="metros">11</anchura>
    <fecha>27 abril</fecha>
    <hora>14:00</hora>
    <numero-vueltas>25</numero-vueltas>
    <localidad>Jerez</localidad>
    <pais>España</pais>
    <patrocinador>Estrella Galicia 0.0</patrocinador>
    <referencias>
        <referencia>https://www.motogp.com/es</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_de_Jerez</referencia>
        <referencia>https://circuitodejerez.com/</referencia>
    </referencias>
    <fotografias>
        <fotografia archivo="multimedia/jerezEsquema.jpg">Esquema del circuito</fotografia>
    </fotografias>
    <videos>
        <video archivo="multimedia/jerezVideo.mp4">Video del circuito</video>
    </videos>



  <punto-origen>
    <longitud-origen>-6.031214</longitud-origen>
    <latitud-origen>36.707242</latitud-origen>
    <altitud-origen>39</altitud-origen>
  </punto-origen>

  <puntos-anonimos>
    <punto>
      <distancia uds="m">34.86</distancia>
      <coordenada>
        <longitud>-6.031361</longitud>
        <latitud>36.706937</latitud>
        <altitud>45</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">32.23</distancia>
      <coordenada>
        <longitud>-6.031731</longitud>
        <latitud>36.706923</latitud>
        <altitud>46</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">311.58</distancia>
      <coordenada>
        <longitud>-6.034042</longitud>
        <latitud>36.709123</latitud>
        <altitud>48</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">180.73</distancia>
      <coordenada>
        <longitud>-6.035991</longitud>
        <latitud>36.709268</latitud>
        <altitud>48</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">46.18</distancia>
      <coordenada>
        <longitud>-6.036501</longitud>
        <latitud>36.709091</latitud>
        <altitud>47</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">301.97</distancia>
      <coordenada>
        <longitud>-6.037939</longitud>
        <latitud>36.706647</latitud>
        <altitud>44</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">152.57</distancia>
      <coordenada>
        <longitud>-6.036722</longitud>
        <latitud>36.705990</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">30.91</distancia>
      <coordenada>
        <longitud>-6.036403</longitud>
        <latitud>36.706120</latitud>
        <altitud>42</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">183.60</distancia>
      <coordenada>
        <longitud>-6.035629</longitud>
        <latitud>36.707874</latitud>
        <altitud>48</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">102.45</distancia>
      <coordenada>
        <longitud>-6.034826</longitud>
        <latitud>36.708370</latitud>
        <altitud>50</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">59.00</distancia>
      <coordenada>
        <longitud>-6.034161</longitud>
        <latitud>36.708351</latitud>
        <altitud>50</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">195.02</distancia>
      <coordenada>
        <longitud>-6.032612</longitud>
        <latitud>36.706879</latitud>
        <altitud>53</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">64.08</distancia>
      <coordenada>
        <longitud>-6.032354</longitud>
        <latitud>36.706323</latitud>
        <altitud>47</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">241.19</distancia>
      <coordenada>
        <longitud>-6.033416</longitud>
        <latitud>36.704263</latitud>
        <altitud>46</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">35.16</distancia>
      <coordenada>
        <longitud>-6.033057</longitud>
        <latitud>36.704080</latitud>
        <altitud>41</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">614.55</distancia>
      <coordenada>
        <longitud>-6.027324</longitud>
        <latitud>36.707846</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">91.77</distancia>
      <coordenada>
        <longitud>-6.027274</longitud>
        <latitud>36.708663</latitud>
        <altitud>36</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">49.50</distancia>
      <coordenada>
        <longitud>-6.027651</longitud>
        <latitud>36.709002</latitud>
        <altitud>36</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">353.25</distancia>
      <coordenada>
        <longitud>-6.031326</longitud>
        <latitud>36.709527</latitud>
        <altitud>37</altitud>
      </coordenada>
      <sector>94</sector>
    </punto>

    <punto>
      <distancia uds="m">85.42</distancia>
      <coordenada>
        <longitud>-6.031959</longitud>
        <latitud>36.710087</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">188.00</distancia>
      <coordenada>
        <longitud>-6.032053</longitud>
        <latitud>36.711767</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">64.19</distancia>
      <coordenada>
        <longitud>-6.031346</longitud>
        <latitud>36.712266</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">36.35</distancia>
      <coordenada>
        <longitud>-6.031185</longitud>
        <latitud>36.712572</latitud>
        <altitud>34</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">29.30</distancia>
      <coordenada>
        <longitud>-6.031395</longitud>
        <latitud>36.712763</latitud>
        <altitud>34</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">213.47</distancia>
      <coordenada>
        <longitud>-6.033731</longitud>
        <latitud>36.712717</latitud>
        <altitud>37</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">36.45</distancia>
      <coordenada>
        <longitud>-6.033885</longitud>
        <latitud>36.712399</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">306.65</distancia>
      <coordenada>
        <longitud>-6.032533</longitud>
        <latitud>36.709708</latitud>
        <altitud>41</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">298.33</distancia>
      <coordenada>
        <longitud>-6.031214</longitud>
        <latitud>36.707242</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>
    </puntos-anonimos>

    <vencedor>
        <nombre>Alex Marquez</nombre>
        <tiempo>00:40:56:374</tiempo>
    </vencedor>
    <clasificacion>
        <nombre>Alex Marquez</nombre>
        <nombre>Marc Marquez</nombre>
        <nombre>Pecco Bagnaia</nombre>
    </clasificacion>
</circuito>
