=== SSergio0-UO/sew/MotoGP-Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre,longitud-pista,anchura,fecha,hora,
numero-vueltas, localidad, pais, patrocinador,referencias,
 fotografias, videos, punto-origen,puntos-anonimos, vencedor,clasificacion)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud-pista (#PCDATA)>
<!ATTLIST longitud-pista uds CDATA #REQUIRED>

<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura uds CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>
<!ELEMENT numero-vueltas (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT fotografias (fotografia+)>
<!ELEMENT fotografia (#PCDATA)>
<!ATTLIST fotografia archivo CDATA #REQUIRED>

<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video archivo CDATA #REQUIRED>

<!ELEMENT punto-origen (longitud-origen,latitud-origen,altitud-origen)>
<!ELEMENT longitud-origen (#PCDATA)>
<!ELEMENT latitud-origen (#PCDATA)>
<!ELEMENT altitud-origen (#PCDATA)>

<!ELEMENT puntos-anonimos (punto+)>
<!ELEMENT punto (distancia, coordenada, sector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia uds CDATA #REQUIRED>
<!ELEMENT coordenada (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT sector (#PCDATA)>

<!ELEMENT vencedor (nombre, tiempo)>
<!ELEMENT tiempo (#PCDATA)>

<!ELEMENT clasificacion (nombre+)>

=== SSergio0-UO/sew/MotoGP-Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>
    <nombre>Jerez-Angel Nieto</nombre>
    <longitud-pista uds="Kilometros">4,42</longitud-pista>
    <anchura uds="metros">11</anchura>
    <fecha>27 abril</fecha>
    <hora>14:00</hora>
    <numero-vueltas>25</numero-vueltas>
    <localidad>Jerez</localidad>
    <pais>España</pais>
    <patrocinador>Estrella Galicia 0.0</patrocinador>
    <referencias>
        <referencia>https://www.motogp.com/es</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_de_Jerez</referencia>
        <referencia>https://circuitodejerez.com/</referencia>
    </referencias>
    <fotografias>
        <fotografia archivo="multimedia/jerezEsquema.jpg">Esquema del circuito</fotografia>
    </fotografias>
    <videos>
        <video archivo="multimedia/jerezVideo.mp4">Video del circuito</video>
    </videos>
      <punto-origen>
    <longitud-origen>-6.031214</longitud-origen>
    <latitud-origen>36.707242</latitud-origen>
    <altitud-origen>39</altitud-origen>
  </punto-origen>

  <puntos-anonimos>
    <punto>
      <distancia uds="m">34.86</distancia>
      <coordenada>
        <longitud>-6.031361</longitud>
        <latitud>36.706937</latitud>
        <altitud>45</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">32.23</distancia>
      <coordenada>
        <longitud>-6.031731</longitud>
        <latitud>36.706923</latitud>
        <altitud>46</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">311.58</distancia>
      <coordenada>
        <longitud>-6.034042</longitud>
        <latitud>36.709123</latitud>
        <altitud>48</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">180.73</distancia>
      <coordenada>
        <longitud>-6.035991</longitud>
        <latitud>36.709268</latitud>
        <altitud>48</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">46.18</distancia>
      <coordenada>
        <longitud>-6.036501</longitud>
        <latitud>36.709091</latitud>
        <altitud>47</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">301.97</distancia>
      <coordenada>
        <longitud>-6.037939</longitud>
        <latitud>36.706647</latitud>
        <altitud>44</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">152.57</distancia>
      <coordenada>
        <longitud>-6.036722</longitud>
        <latitud>36.705990</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">30.91</distancia>
      <coordenada>
        <longitud>-6.036403</longitud>
        <latitud>36.706120</latitud>
        <altitud>42</altitud>
      </coordenada>
      <sector>1</sector>
    </punto>

    <punto>
      <distancia uds="m">183.60</distancia>
      <coordenada>
        <longitud>-6.035629</longitud>
        <latitud>36.707874</latitud>
        <altitud>48</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">102.45</distancia>
      <coordenada>
        <longitud>-6.034826</longitud>
        <latitud>36.708370</latitud>
        <altitud>50</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">59.00</distancia>
      <coordenada>
        <longitud>-6.034161</longitud>
        <latitud>36.708351</latitud>
        <altitud>0.0</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">195.02</distancia>
      <coordenada>
        <longitud>-6.032612</longitud>
        <latitud>36.706879</latitud>
        <altitud>53</altitud>
      </coordenada>
      <sector>2</sector>
    </punto>

    <punto>
      <distancia uds="m">64.08</distancia>
      <coordenada>
        <longitud>-6.032354</longitud>
        <latitud>36.706323</latitud>
        <altitud>47</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">241.19</distancia>
      <coordenada>
        <longitud>-6.033416</longitud>
        <latitud>36.704263</latitud>
        <altitud>46</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">35.16</distancia>
      <coordenada>
        <longitud>-6.033057</longitud>
        <latitud>36.704080</latitud>
        <altitud>41</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">614.55</distancia>
      <coordenada>
        <longitud>-6.027324</longitud>
        <latitud>36.707846</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">91.77</distancia>
      <coordenada>
        <longitud>-6.027274</longitud>
        <latitud>36.708663</latitud>
        <altitud>36</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">49.50</distancia>
      <coordenada>
        <longitud>-6.027651</longitud>
        <latitud>36.709002</latitud>
        <altitud>36</altitud>
      </coordenada>
      <sector>3</sector>
    </punto>

    <punto>
      <distancia uds="m">353.25</distancia>
      <coordenada>
        <longitud>-6.031326</longitud>
        <latitud>36.709527</latitud>
        <altitud>37</altitud>
      </coordenada>
      <sector>94</sector>
    </punto>

    <punto>
      <distancia uds="m">85.42</distancia>
      <coordenada>
        <longitud>-6.031959</longitud>
        <latitud>36.710087</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">188.00</distancia>
      <coordenada>
        <longitud>-6.032053</longitud>
        <latitud>36.711767</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">64.19</distancia>
      <coordenada>
        <longitud>-6.031346</longitud>
        <latitud>36.712266</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">36.35</distancia>
      <coordenada>
        <longitud>-6.031185</longitud>
        <latitud>36.712572</latitud>
        <altitud>34</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">29.30</distancia>
      <coordenada>
        <longitud>-6.031395</longitud>
        <latitud>36.712763</latitud>
        <altitud>34</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">213.47</distancia>
      <coordenada>
        <longitud>-6.033731</longitud>
        <latitud>36.712717</latitud>
        <altitud>37</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">36.45</distancia>
      <coordenada>
        <longitud>-6.033885</longitud>
        <latitud>36.712399</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">306.65</distancia>
      <coordenada>
        <longitud>-6.032533</longitud>
        <latitud>36.709708</latitud>
        <altitud>41</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>

    <punto>
      <distancia uds="m">298.33</distancia>
      <coordenada>
        <longitud>-6.031214</longitud>
        <latitud>36.707242</latitud>
        <altitud>40</altitud>
      </coordenada>
      <sector>4</sector>
    </punto>
    </puntos-anonimos>

    <vencedor>
        <nombre>Alex Marquez</nombre>
        <tiempo>00:40:56:374</tiempo>
    </vencedor>
    <clasificacion>
        <nombre>Alex Marquez</nombre>
        <nombre>Marc Marquez</nombre>
        <nombre>Pecco Bagnaia</nombre>
    </clasificacion>
</circuito>
