=== SSergio0-UO/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre,longitud,anchura,fecha,hora,
numero-vueltas, localidad, pais, patrocinador,referencias,
 fotografias,fotografias, videos, punto-origen, vencedor,clasificacion)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud uds CDATA #REQUIRED>

<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura uds CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>
<!ELEMENT numero-vueltas (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT fotografias (fotografia+)>
<!ELEMENT fotografia (#PCDATA)>
<!ATTLIST fotografia archivo CDATA #REQUIRED>

<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video archivo CDATA #REQUIRED>

<!ELEMENT punto-origen (longitud-origen,latitud-origen,altitud-origen)>
<!ELEMENT longitud-origen (#PCDATA)>
<!ELEMENT latitud-origen (#PCDATA)>
<!ELEMENT altitud-origen (#PCDATA)>

<!ELEMENT puntos-anonimos (punto+)>

<!ELEMENT vencedor (nombre, tiempo)>
<!ELEMENT tiempo (#PCDATA)>

<!ELEMENT clasificacion (nombre+)>

=== SSergio0-UO/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>
    <nombre>Jerez-Angel Nieto</nombre>
    <longitud uds="Kilometros">4,42</longitud>
    <anchura uds="metros">11</anchura>
    <fecha>27 abril</fecha>
    <hora>14:00</hora>
    <numero-vueltas>25</numero-vueltas>
    <localidad>Jerez</localidad>
    <pais>España</pais>
    <patrocinador>Estrella Galicia 0.0</patrocinador>
    <referencias>
        <referencia>https://www.motogp.com/es</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_de_Jerez</referencia>
        <referencia>https://circuitodejerez.com/</referencia>
    </referencias>
    <fotografias>
        <fotografia archivo="multimedia/jerezEsquema.jpg">Esquema del circuito</fotografia>
    </fotografias>
    <videos>
        <video archivo="tbd">tbd</video>
    </videos>
    <punto-origen>
        <longitud-origen>6º 01' 56"</longitud-origen>
        <latitud-origen>36º 42' 34"</latitud-origen>
        <altitud-origen>39</altitud-origen>
    </punto-origen>
    <vencedor>
        <nombre>Alex Marquez</nombre>
        <tiempo>00:40:56:374</tiempo>
    </vencedor>
    <clasificacion>
        <nombre>Alex Marquez</nombre>
        <nombre>Marc Marquez</nombre>
        <nombre>Pecco Bagnaia</nombre>
    </clasificacion>
</circuito>
